version: '3'
services:
  node_server:
    container_name: nodejs
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - './:/app'
      - '/app/node_modules'
    ports:
      - 8000:8000
    environment:
      - NODE_ENV=dev
    entrypoint: [ "yarn", "dev" ]

  # Elasticsearch
  elasticsearch:
    image: elasticsearch:7.8.0
    container_name: elasticsearch
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
      - ./elastic/elasticsearch.yaml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9200:9200
    environment:
      discovery.type: single-node

  kibana:
    image: docker.elastic.co/kibana/kibana:7.8.0
    container_name: kibana
    volumes:
      - ./elastic/kibana.yaml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601

  logstash:
    image: logstash:7.8.1
    container_name: logstash
    volumes:
      - ./elastic/logging.conf:/usr/share/logstash/pipeline/logging.conf
      - ./elastic/logstash.yaml:/usr/share/logstash/config/logstash.yml
    ports:
      - 1514:1514/udp
      - 1515:1515
      - 1515:1515/udp

volumes:
  elasticsearch_data:
    driver: local
